# skip boilerplate check
---
# start of document (---) avoids errors if the file only contains comments

# yaml-language-server: $schema=../../../../schemas/vpc.schema.json

project_id: $project_ids:net-core-0
name: mgmt
delete_default_routes_on_create: false
mtu: 1500
