# Copyright 2025 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# yaml-language-server: $schema=../../stages/2-project-factory/schemas/project.schema.json

# TODO: edit and uncomment the following line to create the project in a folder
# parent: shared

name: prod-os-apt-0
services:
  - accesscontextmanager.googleapis.com
  - artifactregistry.googleapis.com

automation:
  # TODO: edit the automation project and optionally edit resource names
  project: prod-pf-iac-0
  service_accounts:
    rw:
      description: Read/write automation service account for apt registries.
  bucket:
    description: Terraform state bucket for apt registries.
    iam:
      roles/storage.objectCreator:
        - rw
      roles/storage.objectViewer:
        - rw
iam:
  roles/viewer:
    - prod-os-apt-0/rw
  roles/artifactregistry.admin:
    - prod-os-apt-0/rw
  # TODO: add instance service accounts that need access to the registries
  # roles/artifactregistry.writer:
  #   - serviceAccount:foo@bar