# skip boilerplate check

# yaml-language-server: $schema=../../../../../schemas/subnet.schema.json

name: prod-default
region: $locations:primary
ip_cidr_range: 10.72.0.0/24
description: Default primary-region subnet for prod
# flow_logs_config:
#   aggregation_interval: "INTERVAL_5_SEC"
#   flow_sampling: 1.0
#   metadata: "INCLUDE_ALL_METADATA"
