# skip boilerplate check

# yaml-language-server: $schema=../../../../../schemas/subnet.schema.json

name: prod-default
region: $locations:primary
ip_cidr_range: 10.72.0.0/24
description: Default europe-west12 subnet for prod
